In [5]:
#import important libraries that are needed 

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [47]:
#impotrt model for the training and test for model

from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [49]:
#use classifier to train the model and also check the score means the accuracy of the model

lr = LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)
lr.score(x_test, y_test)

0.9629629629629629

In [51]:
#now lets use another model and check its accuracy
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9907407407407407

In [53]:
#lets try Randomforest
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9796296296296296

In [55]:
#now lets try the main thing we are trying to understand i KFold

from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf


KFold(n_splits=5, random_state=None, shuffle=False)

In [57]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index, test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [123]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [109]:
#these are just to check the models performance these are done only for checking score of each model
#get_score(LogisticRegression(max_iter=1000), x_train, x_test, y_train, y_test)

0.9629629629629629

In [111]:
#get_score(SVC(), x_train, x_test, y_train, y_test)

0.9907407407407407

In [113]:
#get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test)

0.975925925925926

In [151]:
#here we check the KFold models score 
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)


In [169]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                       digits.target[train_index], digits.target[test_index]

    
    scores_lr.append(get_score(LogisticRegression(max_iter=1000), x_train, x_test, y_train, y_test))
    
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [170]:
#these are the scores of each model i have choosed split=5 means it will me 5 scores of each data which comes in

scores_lr

[0.9277777777777778,
 0.875,
 0.9415041782729805,
 0.9387186629526463,
 0.9080779944289693]

In [173]:
scores_svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [175]:
scores_rf

[0.9166666666666666,
 0.9166666666666666,
 0.9498607242339833,
 0.9526462395543176,
 0.9080779944289693]

In [185]:
#sklearn library give us a built method for score checking which is cross_val_score if we use this we don't need to write too much like we have done
#before so lets try it. you also can call it a model

from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

#you also can check the scores of other models like SVC(), and RandomForestClassifier()

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])